image: adfreiburg/qlever:commit-99b6db5
command:
  - bash
configmap:
  /qlever/frink-qlever.settings.json: |
    { "ascii-prefixes-only": false, "num-triples-per-batch": 10000, "parser-integer-overflow-behavior": "overflowing-integers-become-doubles" }


