apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app_config.local_pvc_name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.app_config.local_pvc_size }}