kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kace.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
    - configmaps
    - pods
    - secrets
    - services
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - "apps"
  resources:
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - "networking.k8s.io"
  resources:
    - "ingresses"
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kace.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "kace.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kace.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io